// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQM',
    appId: '1:297855924061:web:669618f2db89dd5b9ac3a6',
    messagingSenderId: '297855924061',
    projectId: 'tastesmoke-app',
    authDomain: 'tastesmoke-app.firebaseapp.com',
    storageBucket: 'tastesmoke-app.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQM',
    appId: '1:297855924061:android:ac3b2b77e34bae4c9ac3a6',
    messagingSenderId: '297855924061',
    projectId: 'tastesmoke-app',
    authDomain: 'tastesmoke-app.firebaseapp.com',
    storageBucket: 'tastesmoke-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQM',
    appId: '1:297855924061:ios:ac3b2b77e34bae4c9ac3a6',
    messagingSenderId: '297855924061',
    projectId: 'tastesmoke-app',
    authDomain: 'tastesmoke-app.firebaseapp.com',
    storageBucket: 'tastesmoke-app.appspot.com',
    iosBundleId: 'com.tastesmoke.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrjn-0hI9ctcWDNIdKJQM',
    appId: '1:297855924061:ios:ac3b2b77e34bae4c9ac3a6',
    messagingSenderId: '297855924061',
    projectId: 'tastesmoke-app',
    authDomain: 'tastesmoke-app.firebaseapp.com',
    storageBucket: 'tastesmoke-app.appspot.com',
    iosBundleId: 'com.tastesmoke.app',
  );
}
